# 메뉴 데이터 정의
diet_lists = {
    "vegan": ["두부 단호박 샐러디", "두부 포케볼", "감자튀김", "콜라", "사이다"],
    "vegetarian": ["두부 단호박 샐러디", "두부 포케볼", "감자튀김", "콜라", "사이다", "치즈스틱", "아이스크림", "팥빙수"],
}

# 알레르기 정보 매핑
allergen_map = {
    "청양 통새우버거": ["달걀", "밀", "대두", "우유", "토마토", "새우", "조개류(굴)"],
    "치킨버거": ["달걀", "밀", "대두", "우유", "닭고기", "땅콩", "조개류(가리비)"],
    "데리버거": ["달걀", "밀", "대두", "우유", "닭고기", "조개류(가리비)"],
    "모짜렐라 버거": ["달걀", "밀", "대두", "우유", "쇠고기", "돼지고기"],
    "불고기버거": ["밀", "대두", "달걀", "우유", "토마토", "쇠고기"],
    "멕시칸 랩": ["달걀", "우유", "대두", "밀", "돼지고기", "쇠고기"],
    "연어 포케볼": ["대두", "밀", "연어"],
    "로스트 닭다리살 샐러디": ["우유", "대두", "밀", "토마토", "닭고기", "쇠고기"],
    "두부 단호박 샐러디": ["대두", "밀"],
    "두부 포케볼": ["대두", "호두"],
    "감자튀김": ["대두", "토마토"],
    "치즈스틱": ["밀", "대두", "달걀", "우유"],
    "콜라": [],
    "사이다": [],
    "아이스크림": ["우유", "밀", "대두"],
    "팥빙수": ["우유"],
}

# 알레르기 필터 목록
allergen_list = [
    "달걀", "토마토", "새우", "조개류(굴)", "조개류(가리비)",
    "닭고기", "땅콩", "쇠고기", "돼지고기", "호두",
]

# 메뉴 아이템 데이터
menu_items = [
    # 버거 카테고리
    {
        "id": 1,
        "name": "청양 통새우버거",
        "description": "매콤한 청양고추와 통새우가 들어간 프리미엄 버거",
        "price": 12900,
        "image": "public/spicy-shrimp-burger.png",
        "category": "메인",
        "subcategory": "버거",
        "is_vegan": False,
        "is_allergy_free": False,
        "is_customizable": True,
        "cooking_time": 8,
        "sodium": 850,
    },
    {
        "id": 2,
        "name": "치킨버거",
        "description": "바삭한 치킨 패티와 신선한 야채가 들어간 클래식 버거",
        "price": 8900,
        "image": "public/crispy-chicken-burger.png",
        "category": "메인",
        "subcategory": "버거",
        "is_vegan": False,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 6,
        "sodium": 720,
    },
    {
        "id": 3,
        "name": "데리버거",
        "description": "달콤한 데리야키 소스와 치킨 패티의 조화",
        "price": 9500,
        "image": "public/teriyaki-chicken-burger.png",
        "category": "메인",
        "subcategory": "버거",
        "is_vegan": False,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 7,
        "sodium": 680,
    },
    {
        "id": 4,
        "name": "모짜렐라 버거",
        "description": "진짜 모짜렐라 치즈가 듬뿍 들어간 치즈 버거",
        "price": 10500,
        "image": "public/melting-mozzarella-burger.png",
        "category": "메인",
        "subcategory": "버거",
        "is_vegan": False,
        "is_allergy_free": False,
        "is_customizable": True,
        "cooking_time": 7,
        "sodium": 920,
    },
    {
        "id": 5,
        "name": "불고기버거",
        "description": "한국식 불고기와 신선한 야채가 들어간 프리미엄 버거",
        "price": 11900,
        "image": "public/korean-bulgogi-burger.png",
        "category": "메인",
        "subcategory": "버거",
        "is_vegan": False,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 8,
        "sodium": 780,
    },
    # 랩 카테고리
    {
        "id": 6,
        "name": "멕시칸 랩",
        "description": "매콤한 치킨과 아보카도, 살사소스가 들어간 멕시칸 스타일 랩",
        "price": 8500,
        "image": "public/mexican-beef-pork-wrap.png",
        "category": "메인",
        "subcategory": "랩",
        "is_vegan": False,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 5,
        "sodium": 650,
    },
    # 보울 카테고리
    {
        "id": 7,
        "name": "두부 포케볼",
        "description": "신선한 두부와 각종 야채가 들어간 건강한 포케볼",
        "price": 9900,
        "image": "public/tofu-poke-bowl.png",
        "category": "메인",
        "subcategory": "보울",
        "is_vegan": True,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 4,
        "sodium": 420,
    },
    {
        "id": 8,
        "name": "연어 포케볼",
        "description": "신선한 연어와 아보카도, 현미밥이 들어간 프리미엄 포케볼",
        "price": 13900,
        "image": "public/salmon-poke-bowl.png",
        "category": "메인",
        "subcategory": "보울",
        "is_vegan": False,
        "is_allergy_free": False,
        "is_customizable": True,
        "cooking_time": 5,
        "sodium": 580,
    },
    # 샐러디 카테고리
    {
        "id": 9,
        "name": "로스트 닭다리살 샐러디",
        "description": "부드럽게 구운 닭다리살과 신선한 채소의 조화",
        "price": 11500,
        "image": "public/roasted-chicken-salad.png",
        "category": "메인",
        "subcategory": "샐러디",
        "is_vegan": False,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 6,
        "sodium": 520,
    },
    {
        "id": 10,
        "name": "두부 단호박 샐러디",
        "description": "고소한 두부와 달콤한 단호박이 들어간 건강 샐러드",
        "price": 9500,
        "image": "public/tofu-pumpkin-salad-bowl.png",
        "category": "메인",
        "subcategory": "샐러디",
        "is_vegan": True,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 3,
        "sodium": 380,
    },
    # 사이드 메뉴
    {
        "id": 11,
        "name": "감자튀김",
        "description": "바삭한 황금 감자튀김",
        "price": 3500,
        "image": "public/golden-french-fries.png",
        "category": "사이드",
        "subcategory": None,
        "is_vegan": True,
        "is_allergy_free": True,
        "is_customizable": False,
        "cooking_time": 4,
        "sodium": 320,
    },
    {
        "id": 12,
        "name": "치즈스틱",
        "description": "쫄깃한 모짜렐라 치즈스틱 5개",
        "price": 4500,
        "image": "public/crispy-golden-mozzarella-sticks.png",
        "category": "사이드",
        "subcategory": None,
        "is_vegan": False,
        "is_allergy_free": False,
        "is_customizable": False,
        "cooking_time": 5,
        "sodium": 480,
    },
    # 음료
    {
        "id": 13,
        "name": "콜라",
        "description": "시원한 콜라 500ml",
        "price": 2000,
        "image": "public/refreshing-cola.png",
        "category": "음료",
        "subcategory": None,
        "is_vegan": True,
        "is_allergy_free": True,
        "is_customizable": False,
        "cooking_time": 1,
        "sodium": 15,
    },
    {
        "id": 14,
        "name": "사이다",
        "description": "상쾌한 사이다 500ml",
        "price": 2000,
        "image": "public/refreshing-sprite.png",
        "category": "음료",
        "subcategory": None,
        "is_vegan": True,
        "is_allergy_free": True,
        "is_customizable": False,
        "cooking_time": 1,
        "sodium": 20,
    },
    # 디저트
    {
        "id": 15,
        "name": "아이스크림",
        "description": "부드럽고 달콤한 프리미엄 바닐라 아이스크림",
        "price": 4500,
        "image": "public/vanilla-ice-cream.png",
        "category": "디저트",
        "subcategory": None,
        "is_vegan": False,
        "is_allergy_free": False,
        "is_customizable": False,
        "cooking_time": 1,
        "sodium": 45,
    },
    {
        "id": 16,
        "name": "팥빙수",
        "description": "달콤한 팥과 부드러운 빙수의 완벽한 조화",
        "price": 7500,
        "image": "public/patbingsu.png",
        "category": "디저트",
        "subcategory": None,
        "is_vegan": True,
        "is_allergy_free": True,
        "is_customizable": True,
        "cooking_time": 3,
        "sodium": 25,
    },
]

# 카테고리 목록
categories = ["전체", "메인", "사이드", "음료", "디저트"]

# 메인 서브카테고리 목록
main_subcategories = ["전체", "버거", "랩", "보울", "샐러디"]